### ISSUE TITLE
服务端容器部署的BASE_URL 设置为复杂 URL时报错

### ISSUE THREAD

**Issue by jochne** [Script-Hub-Org/Script-Hub#25]
通过BASE_URL 设置为复杂 URL时

直接访问BASE_URL，提示 Internal Server Error

容器内部报错日志如下
```
 TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
      at Object.openSync (node:fs:588:10)
      at Object.readFileSync (node:fs:464:35)
      at evalFn (/app/service.js:46:20)
      at reqFn (/app/service.js:80:24)
      at /app/service.js:96:9
      at dispatch (/app/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
      at /app/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
      at Application.handleRequest (/app/node_modules/.pnpm/koa@2.15.3/node_modules/koa/lib/application.js:186:12)
      at Server.handleRequest (/app/node_modules/.pnpm/koa@2.15.3/node_modules/koa/lib/application.js:157:21)
      at Server.emit (node:events:517:28)
```

**Comment by xream** [comment]
@jochne 日志不全 这个的上面就是 url
如果是 favicon.ico 那无视它即可

**Comment by xream** [comment]
@jochne 补充: BASE_URL 的设置和 反代的设置要对应
请自己检查

**Comment by jochne** [comment]
## docker-compose.yml
```
services:
  app:
    image: xream/script-hub:latest
    restart: always
    environment:
      - PORT=9100
      - BASE_URL=http://script.xxxxxx.xxxxxx/XhPEtZAkxEknL108
      - BETA_PORT=9101
      - BETA_BASE_URL=http://beta.script.xxxxxx.xxxxxx/XhPEtZAkxEknL108
    ports:
      - "127.0.0.1:9100:9100"  # 主机上的 9100 端口映射到容器的 PORT
      - "127.0.0.1:9101:9101"  # 主机上的 9101端口映射到容器的 BETA_PORT
```

## nginx配置
```
user  www www;
worker_processes auto;
error_log  /www/wwwlogs/nginx_error.log  crit;
pid        /www/server/nginx/logs/nginx.pid;
worker_rlimit_nofile 51200;

stream {
    log_format tcp_format '$time_local|$remote_addr|$protocol|$status|$bytes_sent|$bytes_received|$session_time|$upstream_addr|$upstream_bytes_sent|$upstream_bytes_received|$upstream_connect_time';
  
    access_log /www/wwwlogs/tcp-access.log tcp_format;
    error_log /www/wwwlogs/tcp-error.log;
    include /www/server/panel/vhost/nginx/tcp/*.conf;
}

events {
    use epoll;
    worker_connections 51200;
    multi_accept on;
}

http {
    include       mime.types;
    #include luawaf.conf;

    include proxy.conf;
    lua_package_path "/www/server/nginx/lib/lua/?.lua;;";

    default_type  application/octet-stream;

    server_names_hash_bucket_size 512;
    client_header_buffer_size 32k;
    large_client_header_buffers 4 32k;
    client_max_body_size 50m;

    sendfile   on;
    tcp_nopush on;

    keepalive_timeout 60;

    tcp_nodelay on;

    fastcgi_connect_timeout 300;
    fastcgi_send_timeout 300;
    fastcgi_read_timeout 300;
    fastcgi_buffer_size 64k;
    fastcgi_buffers 4 64k;
    fastcgi_busy_buffers_size 128k;
    fastcgi_temp_file_write_size 256k;
    fastcgi_intercept_errors on;

    gzip on;
    gzip_min_length  1k;
    gzip_buffers     4 16k;
    gzip_http_version 1.1;
    gzip_comp_level 2;
    gzip_types     text/plain application/javascript application/x-javascript text/javascript text/css application/xml application/json image/jpeg image/gif image/png font/ttf font/otf image/svg+xml application/xml+rss text/x-js;
    gzip_vary on;
    gzip_proxied   expired no-cache no-store private auth;
    gzip_disable   "MSIE [1-6]\.";

    limit_conn_zone $binary_remote_addr zone=perip:10m;
    limit_conn_zone $server_name zone=perserver:10m;

    server_tokens off;
    access_log off;

    # 生产环境配置
    server {
        listen 80;
        server_name script.xxxxxx.xxxxxx;

        location /XhPEtZAkxEknL108/ {
            proxy_pass http://127.0.0.1:9100;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    # 测试环境配置
    server {
        listen 80;
        server_name beta.script.xxxxxx.xxxxxx;

        location /XhPEtZAkxEknL108/ {
            proxy_pass http://127.0.0.1:9101;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    include /www/server/panel/vhost/nginx/*.conf;
}
```

## 访问路径：
http://script.xxxxxx.xxxxxx/XhPEtZAkxEknL108/
浏览器返回
```
响应
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Length: 21
Content-Type: text/plain; charset=utf-8
Date: Thu, 14 Nov 2024 02:14:52 GMT
Server: nginx
```

## 容器script-hub-app-1日志
```
> script-hub@1.0.0 service /app
> nodemon service.js

[33m[nodemon] 3.1.7[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching path(s): *.*[39m
[33m[nodemon] watching extensions: js,mjs,cjs,json[39m
[32m[nodemon] starting `node service.js`[39m
listening on port 0.0.0.0:9100, http://127.0.0.1:9100, BASE URL: http://script.xxxxxx.xxxxxx/XhPEtZAkxEknL108
β listening on port 0.0.0.0:9101, http://127.0.0.1:9101, BASE URL: http://beta.script.xxxxxx.xxxxxx/XhPEtZAkxEknL108
url http://script.hub/XhPEtZAkxEknL108/
scriptFilePath undefined

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
at Object.openSync (node:fs:588:10)
at Object.readFileSync (node:fs:464:35)
at evalFn (/app/service.js:46:20)
at reqFn (/app/service.js:80:24)
at /app/service.js:96:9
at dispatch (/app/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
at /app/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
at Application.handleRequest (/app/node_modules/.pnpm/koa@2.15.3/node_modules/koa/lib/application.js:186:12)
at Server.handleRequest (/app/node_modules/.pnpm/koa@2.15.3/node_modules/koa/lib/application.js:157:21)
at Server.emit (node:events:517:28)

url http://script.hub/XhPEtZAkxEknL108/
scriptFilePath undefined

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
at Object.openSync (node:fs:588:10)
at Object.readFileSync (node:fs:464:35)
at evalFn (/app/service.js:46:20)
at reqFn (/app/service.js:80:24)
at /app/service.js:96:9
at dispatch (/app/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
at /app/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
at Application.handleRequest (/app/node_modules/.pnpm/koa@2.15.3/node_modules/koa/lib/application.js:186:12)
at Server.handleRequest (/app/node_modules/.pnpm/koa@2.15.3/node_modules/koa/lib/application.js:157:21)
at Server.emit (node:events:517:28)
```


以上错误，移除path后不会出现，可正常访问

**Comment by xream** [comment]
`proxy_pass` 后面少了 `/`

**Comment by jochne** [comment]
多谢大佬，那一行修改为 `proxy_pass http://127.0.0.1:9100/;` 后可以正常访问了
